apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
  labels:
    app: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: fizbasaeed2005-source/devops_midsproject:fa23-bcs-053
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_ENV
          value: "production"
